name: Secure Pipeline

on:
  pull_request: # Zorgt ervoor dat de workflow bij elke pull request draait
    branches:
      - main
      - dev

jobs:
  sast_scan:
    name: Run SAST and Security Checks
    runs-on: ubuntu-latest # Gebruik Ubuntu voor bredere compatibiliteit

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    # 5. Check dependencies for vulnerabilities (Safety)
    - name: Check Dependencies
      run: |
        pip install safety
        safety check --full-report


